backend:
  name: github
  repo: starboardcoop/riceo

local_backend: true

media_folder: static/assets
public_folder: /assets

collections:
  - name: about
    label: About
    folder: markdown/about
    create: true
    fields:
      - { name: id, label: ID }
      - { name: title, label: Title }
      - { name: order, label: Order, widget: number }
      - { name: body, label: Body, widget: markdown }