backend:
  name: github
  repo: starboardcoop/riceo

local_backend: true

media_folder: static/assets
public_folder: /assets

collections:
  - name: home
    label: Home
    folder: src/markdown/home
    create: true
    editor:
      preview: false
    fields:
      - { name: id, label: ID }
      - { name: title, label: Title }
      - { name: order, label: Order, widget: number }
      - { name: body, label: Body, widget: markdown }
  - name: about
    label: About
    folder: src/markdown/about
    create: true
    editor:
      preview: false
    fields:
      - { name: id, label: ID }
      - { name: title, label: Title }
      - { name: order, label: Order, widget: number }
      - { name: body, label: Body, widget: markdown }
  - name: learn
    label: Learn
    folder: src/markdown/learn
    create: true
    editor:
      preview: false
    fields:
      - { name: id, label: ID }
      - { name: title, label: Title }
      - { name: order, label: Order, widget: number }
      - { name: body, label: Body, widget: markdown }
  - name: resources
    label: Resources
    folder: src/markdown/resources
    create: true
    editor:
      preview: false
    fields:
      - { name: id, label: ID }
      - { name: title, label: Title }
      - { name: order, label: Order, widget: number }
      - { name: body, label: Body, widget: markdown }
  - name: news
    label: News
    folder: src/markdown/news
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle}
      - { name: image, label: Image, widget: image }
      - { name: link, label: Link }
      - { name: date, label: Date , widget: date }
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - label: Navigation
        name: navigation 
        file: src/settings/navigation/navigation.json
        fields:
          - label: Logo
            name: logo
            widget: object
            fields: 
              - {label: "Alt Text", name: alt}
          - label: Links
            name: links
            widget: list
            fields: 
              - {label: Label, name: label}
              - {label: Link, name: link}
      - label: Hero
        name: hero
        file: src/settings/hero/hero.json
        fields:
          - label: Slides
            name: slides
            widget: list
            fields:
              - {label: Title, name: title}
              - {label: Subtitle, name: subtitle}
              - {label: Content, name: content, widget: text}
              - label: Button
                name: button
                widget: object
                fields:
                  - {label: Label, name: label}
                  - {label: Link, name: link}